# Generated by Django 4.2.4 on 2023-10-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map',
            field=models.URLField(default='https://www.google.com/maps/place/University+of+Cambridge/@52.2053593,0.1105931,17z/data=!3m1!4b1!4m6!3m5!1s0x47d8774ed42712a9:0x21ca80abf36db5bb!8m2!3d52.205356!4d0.113168!16zL20vMDd0ZzQ?entry=ttu', max_length=500),
        ),
    ]
