# Generated by Django 4.2.4 on 2023-10-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_event_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='map',
            field=models.URLField(max_length=500),
        ),
    ]
