# Generated by Django 4.2.4 on 2023-10-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
